apiVersion: v1
kind: Service
metadata:
  name: happyornot
  labels:
    app: happyornot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: happyornot-http-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: happyornot